return {
    "nvim-treesitter/nvim-treesitter",
    event = { "BufReadPre", "BufNewFile" },
    branch = 'master',
    lazy = false,
    build = ":TSUpdate",

    config = function()
        local treesitter = require("nvim-treesitter.configs")

        treesitter.setup({
            highlight = { 
                enable = true,
                additional_vim_regex_highlighting = true,
            },
            indent = { enable = true },
            ensure_installed = {
                "c",
                "c_sharp",
                "cpp",
                "cmake",
                "comment",
                "csv",
                "css",
                "dockerfile",
                "gitcommit",
                "gitignore",
                "gitattributes",
                "git_rebase",
                "git_config",
                "go",
                "gpg",
                "html",
                "http",
                "hyprlang",
                -- "jinja",
                -- "jinja_inline",
                "ini",
                "jq",
                "json",
                "jsonc",
                "make",
                "meson",
                "nginx",
                "nix",
                "passwd",
                "perl",
                "php",
                "powershell",
                "puppet",
                "python",
                "regex",
                "requirements",
                "ruby",
                "rust",
                "scss",
                "java",
                "javascript",
                "ssh_config",
                "sql",
                "sway",
                "terraform",
                "toml",
                "tmux",
                "typescript",
                "vala",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "yuck",
                "lua",
                "awk",
                "bash",
                "markdown",
                "query",
                "markdown_inline"
            }
        })
    end
}
